name: Advent of code day 1
on: 
  push:
    paths:
      - 'day1/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: cd day1    
      - run: npm ci
      - run: npm run build --if-present
      - run: node day1/a.js
